"""Description of changes

Revision ID: 2b0a27757f1a
Revises: 
Create Date: 2024-02-19 15:53:24.096042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '538cda0b42c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('FISAdmin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Status', sa.String(length=50), nullable=True))
        batch_op.drop_column('IsActive')

    with op.batch_alter_table('FISFaculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Status', sa.String(length=50), nullable=True))
        batch_op.drop_column('IsActive')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('FISFaculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsActive', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('Status')

    with op.batch_alter_table('FISAdmin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsActive', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('Status')
        
    # ### end Alembic commands ###
